from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class NewBook(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None):  # noqa: E501
        """NewBook - a model defined in OpenAPI

        :param title: The title of this NewBook.  # noqa: E501
        :type title: str
        :param author: The author of this NewBook.  # noqa: E501
        :type author: str
        """
        self.openapi_types = {
            'title': str,
            'author': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author'
        }

        self._title = title
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'NewBook':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewBook of this NewBook.  # noqa: E501
        :rtype: NewBook
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this NewBook.

        The title of the book.  # noqa: E501

        :return: The title of this NewBook.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this NewBook.

        The title of the book.  # noqa: E501

        :param title: The title of this NewBook.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this NewBook.

        The author of the book.  # noqa: E501

        :return: The author of this NewBook.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this NewBook.

        The author of the book.  # noqa: E501

        :param author: The author of this NewBook.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author
