# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Book(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, author: str=None, category: str=None, available_copies: int=None):  # noqa: E501
        """Book - a model defined in Swagger

        :param id: The id of this Book.  # noqa: E501
        :type id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param category: The category of this Book.  # noqa: E501
        :type category: str
        :param available_copies: The available_copies of this Book.  # noqa: E501
        :type available_copies: int
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'author': str,
            'category': str,
            'available_copies': int
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'category': 'category',
            'available_copies': 'available_copies'
        }
        self._id = id
        self._title = title
        self._author = author
        self._category = category
        self._available_copies = available_copies

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Book.


        :return: The id of this Book.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Book.


        :param id: The id of this Book.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.


        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.


        :param title: The title of this Book.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.


        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.


        :param author: The author of this Book.
        :type author: str
        """

        self._author = author

    @property
    def category(self) -> str:
        """Gets the category of this Book.


        :return: The category of this Book.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this Book.


        :param category: The category of this Book.
        :type category: str
        """

        self._category = category

    @property
    def available_copies(self) -> int:
        """Gets the available_copies of this Book.


        :return: The available_copies of this Book.
        :rtype: int
        """
        return self._available_copies

    @available_copies.setter
    def available_copies(self, available_copies: int):
        """Sets the available_copies of this Book.


        :param available_copies: The available_copies of this Book.
        :type available_copies: int
        """

        self._available_copies = available_copies
