# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BookCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None, category: str=None, available_copies: int=1):  # noqa: E501
        """BookCreate - a model defined in Swagger

        :param title: The title of this BookCreate.  # noqa: E501
        :type title: str
        :param author: The author of this BookCreate.  # noqa: E501
        :type author: str
        :param category: The category of this BookCreate.  # noqa: E501
        :type category: str
        :param available_copies: The available_copies of this BookCreate.  # noqa: E501
        :type available_copies: int
        """
        self.swagger_types = {
            'title': str,
            'author': str,
            'category': str,
            'available_copies': int
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'category': 'category',
            'available_copies': 'available_copies'
        }
        self._title = title
        self._author = author
        self._category = category
        self._available_copies = available_copies

    @classmethod
    def from_dict(cls, dikt) -> 'BookCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookCreate of this BookCreate.  # noqa: E501
        :rtype: BookCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookCreate.


        :return: The title of this BookCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookCreate.


        :param title: The title of this BookCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookCreate.


        :return: The author of this BookCreate.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookCreate.


        :param author: The author of this BookCreate.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def category(self) -> str:
        """Gets the category of this BookCreate.


        :return: The category of this BookCreate.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this BookCreate.


        :param category: The category of this BookCreate.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def available_copies(self) -> int:
        """Gets the available_copies of this BookCreate.


        :return: The available_copies of this BookCreate.
        :rtype: int
        """
        return self._available_copies

    @available_copies.setter
    def available_copies(self, available_copies: int):
        """Sets the available_copies of this BookCreate.


        :param available_copies: The available_copies of this BookCreate.
        :type available_copies: int
        """

        self._available_copies = available_copies
