# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BorrowRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, book_id: int=None):  # noqa: E501
        """BorrowRequest - a model defined in Swagger

        :param user_id: The user_id of this BorrowRequest.  # noqa: E501
        :type user_id: int
        :param book_id: The book_id of this BorrowRequest.  # noqa: E501
        :type book_id: int
        """
        self.swagger_types = {
            'user_id': int,
            'book_id': int
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'book_id': 'book_id'
        }
        self._user_id = user_id
        self._book_id = book_id

    @classmethod
    def from_dict(cls, dikt) -> 'BorrowRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BorrowRequest of this BorrowRequest.  # noqa: E501
        :rtype: BorrowRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this BorrowRequest.


        :return: The user_id of this BorrowRequest.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this BorrowRequest.


        :param user_id: The user_id of this BorrowRequest.
        :type user_id: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def book_id(self) -> int:
        """Gets the book_id of this BorrowRequest.


        :return: The book_id of this BorrowRequest.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this BorrowRequest.


        :param book_id: The book_id of this BorrowRequest.
        :type book_id: int
        """
        if book_id is None:
            raise ValueError("Invalid value for `book_id`, must not be `None`")  # noqa: E501

        self._book_id = book_id
