# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Loan(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, user_id: int=None, book_id: int=None, borrow_date: datetime=None, return_date: datetime=None):  # noqa: E501
        """Loan - a model defined in Swagger

        :param id: The id of this Loan.  # noqa: E501
        :type id: int
        :param user_id: The user_id of this Loan.  # noqa: E501
        :type user_id: int
        :param book_id: The book_id of this Loan.  # noqa: E501
        :type book_id: int
        :param borrow_date: The borrow_date of this Loan.  # noqa: E501
        :type borrow_date: datetime
        :param return_date: The return_date of this Loan.  # noqa: E501
        :type return_date: datetime
        """
        self.swagger_types = {
            'id': int,
            'user_id': int,
            'book_id': int,
            'borrow_date': datetime,
            'return_date': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'user_id',
            'book_id': 'book_id',
            'borrow_date': 'borrow_date',
            'return_date': 'return_date'
        }
        self._id = id
        self._user_id = user_id
        self._book_id = book_id
        self._borrow_date = borrow_date
        self._return_date = return_date

    @classmethod
    def from_dict(cls, dikt) -> 'Loan':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Loan of this Loan.  # noqa: E501
        :rtype: Loan
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Loan.


        :return: The id of this Loan.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Loan.


        :param id: The id of this Loan.
        :type id: int
        """

        self._id = id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Loan.


        :return: The user_id of this Loan.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Loan.


        :param user_id: The user_id of this Loan.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def book_id(self) -> int:
        """Gets the book_id of this Loan.


        :return: The book_id of this Loan.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this Loan.


        :param book_id: The book_id of this Loan.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def borrow_date(self) -> datetime:
        """Gets the borrow_date of this Loan.


        :return: The borrow_date of this Loan.
        :rtype: datetime
        """
        return self._borrow_date

    @borrow_date.setter
    def borrow_date(self, borrow_date: datetime):
        """Sets the borrow_date of this Loan.


        :param borrow_date: The borrow_date of this Loan.
        :type borrow_date: datetime
        """

        self._borrow_date = borrow_date

    @property
    def return_date(self) -> datetime:
        """Gets the return_date of this Loan.


        :return: The return_date of this Loan.
        :rtype: datetime
        """
        return self._return_date

    @return_date.setter
    def return_date(self, return_date: datetime):
        """Sets the return_date of this Loan.


        :param return_date: The return_date of this Loan.
        :type return_date: datetime
        """

        self._return_date = return_date
